name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install axios fs

      - name: Update Language Stats
        run: node update-language-stats.js

      - name: Update README
        run: |
          node update-readme.js
          git config --global user.name 'MBBXMESBAH'
          git config --global user.email 'freefireccxml@gmail.com'
          git add README.md
          git commit -m 'Update README with latest language stats'
          git push
